[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "http://gala400.it/*"
  to = "https://gala400.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.gala400.it/*"
  to = "https://gala400.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gala400.it/*"
  to = "https://gala400.it/:splat"
  status = 301
  force = true
