/** Gala 400 — dati centrali per generazione sito */
export const SITE = {
  domain: 'https://gala400.it',
  phone: '349 420 8551',
  phoneTel: '+393494208551',
  phoneE164: '+393494208551',
  whatsapp: '393494208551',
  businessName: 'Gala 400 — Idraulico Verona',
  legalName: 'Gala 400 Srls',
  piva: '05180000233',
  rea: 'VR476830',
  gbp: 'https://share.google/IhkhBfXpcJHccJPsL',
  gtag: 'AW-18106797178',
  conversion: 'AW-18106797178/tG61CLym4LocEPqY_7lD',
  /** ID cliente Google Ads (10 cifre). Oppure file google-ads/customer-id.txt */
  googleAdsCustomerId: '',
  promo: 'Promo -20% fino al 28/06',
  arrivalMin: 20,
  yearsExperience: '15+',
  sinceYear: '2010',
  geo: { lat: 45.4384, lng: 10.9916 },
  webAgency: {
    name: 'RF DIGITAL',
    url: 'https://www.rfdigital.it',
  },
};

/** Servizi idraulici e termici */
export const SERVIZI = [
  {
    slug: 'pronto-intervento-idraulico',
    name: 'Pronto intervento idraulico',
    category: 'urgenze',
    urgent: true,
    short: 'Intervento rapido h24 per emergenze acqua, gas e scarichi.',
  },
  {
    slug: 'perdite-acqua-urgenti',
    name: 'Riparazione perdite acqua',
    category: 'urgenze',
    urgent: true,
    short: 'Perdite da tubature, rubinetti, sanitari e impianti condominiali.',
  },
  {
    slug: 'ricerca-perdite-acqua',
    name: 'Ricerca perdite acqua',
    category: 'urgenze',
    urgent: true,
    short: 'Individuazione perdite occulte con strumentazione professionale.',
  },
  {
    slug: 'ricerca-perdite-gas',
    name: 'Ricerca perdite gas',
    category: 'urgenze',
    urgent: true,
    short: 'Verifica impianti a gas e messa in sicurezza certificata.',
  },
  {
    slug: 'emergenza-gas',
    name: 'Emergenza gas',
    category: 'urgenze',
    urgent: true,
    short: 'Intervento immediato in caso di odore gas o sospetta perdita.',
  },
  {
    slug: 'allagamento',
    name: 'Riparazione allagamenti',
    category: 'urgenze',
    urgent: true,
    short: 'Gestione allagamenti, chiusura perdite e ripristino impianto.',
  },
  {
    slug: 'spurgo-urgente',
    name: 'Spurgo e disostruzione',
    category: 'urgenze',
    urgent: true,
    short: 'Spurgo fognature, scarichi intasati e condotte ostruite.',
  },
  {
    slug: 'wc-intasato-urgente',
    name: 'WC e scarichi intasati',
    category: 'urgenze',
    urgent: true,
    short: 'Disotturazione WC, lavandini, docce e collegamenti fognari.',
  },
  {
    slug: 'assistenza-caldaia',
    name: 'Assistenza caldaia',
    category: 'caldaie',
    urgent: true,
    short: 'Caldaia spenta, blocco o guasto: diagnosi e ripristino h24.',
  },
  {
    slug: 'riparazione-caldaia',
    name: 'Riparazione caldaia',
    category: 'caldaie',
    urgent: true,
    short: 'Riparazione guasti, valvole, circolatori e componenti gas.',
  },
  {
    slug: 'manutenzione-caldaia',
    name: 'Manutenzione caldaia',
    category: 'caldaie',
    urgent: false,
    short: 'Controllo fumi, pulizia e rendimento secondo normativa.',
  },
  {
    slug: 'installazione-caldaia',
    name: 'Installazione caldaia',
    category: 'caldaie',
    urgent: false,
    short: 'Sostituzione e installazione caldaie a condensazione.',
  },
  {
    slug: 'scaldabagno',
    name: 'Scaldabagno',
    category: 'termico',
    urgent: true,
    short: 'Installazione, riparazione e sostituzione scaldabagni.',
  },
  {
    slug: 'manutenzione-impianti-idraulici',
    name: 'Manutenzione impianti idraulici',
    category: 'manutenzione',
    urgent: false,
    short: 'Controlli periodici per abitazioni, negozi e condomini.',
  },
  {
    slug: 'rubinetteria',
    name: 'Rubinetteria e sanitari',
    category: 'manutenzione',
    urgent: true,
    short: 'Miscelatori, rubinetti, box doccia e accessori bagno.',
  },
  {
    slug: 'idraulico-condominio',
    name: 'Idraulico per condomini',
    category: 'manutenzione',
    urgent: true,
    short: 'Colonne, centrali termiche e interventi per amministratori.',
  },
];

/** Marche caldaie più diffuse in Italia */
export const MARCHE = [
  { slug: 'vaillant', name: 'Vaillant', country: 'Germania' },
  { slug: 'baxi', name: 'Baxi', country: 'Italia' },
  { slug: 'ariston', name: 'Ariston', country: 'Italia' },
  { slug: 'beretta', name: 'Beretta', country: 'Italia' },
  { slug: 'immergas', name: 'Immergas', country: 'Italia' },
  { slug: 'bosch-junkers', name: 'Bosch / Junkers', country: 'Germania' },
  { slug: 'riello', name: 'Riello', country: 'Italia' },
  { slug: 'ferroli', name: 'Ferroli', country: 'Italia' },
  { slug: 'saunier-duval', name: 'Saunier Duval', country: 'Francia' },
  { slug: 'viessmann', name: 'Viessmann', country: 'Germania' },
  { slug: 'chaffoteaux', name: 'Chaffoteaux', country: 'Francia' },
  { slug: 'de-dietrich', name: 'De Dietrich', country: 'Francia' },
  { slug: 'sime', name: 'Sime', country: 'Italia' },
  { slug: 'lamborghini', name: 'Lamborghini Calore', country: 'Italia' },
  { slug: 'sylber', name: 'Sylber', country: 'Italia' },
  { slug: 'hermann', name: 'Hermann', country: 'Italia' },
  { slug: 'unical', name: 'Unical', country: 'Italia' },
  { slug: 'biasi', name: 'Biasi', country: 'Italia' },
  { slug: 'fondital', name: 'Fondital', country: 'Italia' },
  { slug: 'thermorossi', name: 'Thermorossi', country: 'Italia' },
  { slug: 'italtherm', name: 'Italtherm', country: 'Italia' },
  { slug: 'cosmogas', name: 'Cosmogas', country: 'Italia' },
  { slug: 'hoval', name: 'Hoval', country: 'Svizzera' },
  { slug: 'nova-florida', name: 'Nova Florida', country: 'Italia' },
  { slug: 'ideal', name: 'Ideal', country: 'Regno Unito' },
  { slug: 'westen', name: 'Westen', country: 'Italia' },
  { slug: 'fer', name: 'Fer', country: 'Italia' },
  { slug: 'protherm', name: 'Protherm', country: 'Rep. Ceca' },
  { slug: 'pensotti', name: 'Pensotti', country: 'Italia' },
  { slug: 'ecosolar', name: 'Ecosolar / Kpellet', country: 'Italia' },
];

export const CALDAIA_TIPI = [
  { slug: 'assistenza', name: 'Assistenza', verb: 'assistenza' },
  { slug: 'manutenzione', name: 'Manutenzione', verb: 'manutenzione' },
  { slug: 'riparazione', name: 'Riparazione', verb: 'riparazione' },
];

/** Quartieri e comuni serviti */
export const QUARTIERI = [
  { slug: 'verona-centro', name: 'Verona Centro', type: 'quartiere', highlight: 'centro storico e zone UNESCO' },
  { slug: 'borgo-trento', name: 'Borgo Trento', type: 'quartiere', highlight: 'area ospedaliera e residenziale nord' },
  { slug: 'borgo-roma', name: 'Borgo Roma', type: 'quartiere', highlight: 'zona universitaria e Policlinico' },
  { slug: 'san-zeno', name: 'San Zeno', type: 'quartiere', highlight: 'Basilica e quartieri storici' },
  { slug: 'valdonega', name: 'Valdonega', type: 'quartiere', highlight: 'colline e abitazioni panoramiche' },
  { slug: 'cittadella', name: 'Cittadella', type: 'quartiere', highlight: 'Porta Palio e servizi centrali' },
  { slug: 'filippini', name: 'Filippini', type: 'quartiere', highlight: 'residenziale ben collegato' },
  { slug: 'stadio', name: 'Stadio', type: 'quartiere', highlight: 'Bentegodi e area fieristica' },
  { slug: 'quadrante-europa', name: 'Quadrante Europa', type: 'quartiere', highlight: 'condomini e grande traffico' },
  { slug: 'san-michele', name: 'San Michele', type: 'quartiere', highlight: 'est Verona e Tangenziale' },
  { slug: 'golosine', name: 'Golosine', type: 'quartiere', highlight: 'commerciale e residenziale est' },
  { slug: 'parona', name: 'Parona', type: 'quartiere', highlight: 'sviluppo residenziale sud' },
  { slug: 'chievo', name: 'Chievo', type: 'quartiere', highlight: 'frazione a ovest del centro' },
  { slug: 'san-paolo', name: 'San Paolo', type: 'quartiere', highlight: 'sud-ovest di Verona' },
  { slug: 'mizzole', name: 'Mizzole', type: 'quartiere', highlight: 'nord-est in espansione' },
  { slug: 'montorio', name: 'Montorio', type: 'quartiere', highlight: 'versante collinare est' },
  { slug: 'san-massimo', name: 'San Massimo', type: 'quartiere', highlight: 'residenziale ad alta densità' },
  { slug: 'ca-di-david', name: "Ca' di David", type: 'quartiere', highlight: 'ville e condomini collinari' },
  { slug: 'santa-lucia', name: 'Santa Lucia', type: 'quartiere', highlight: 'ovest città e grandi vie' },
  { slug: 'pindemonte', name: 'Pindemonte', type: 'quartiere', highlight: 'abitazioni e attività locali' },
  { slug: 'borgo-venezia', name: 'Borgo Venezia', type: 'quartiere', highlight: 'asse est e commerci' },
  { slug: 'borgo-milano', name: 'Borgo Milano', type: 'quartiere', highlight: 'quartiere popolare vivace' },
  { slug: 'veronetta', name: 'Veronetta', type: 'quartiere', highlight: 'sponda sinistra Adige' },
  { slug: 'san-pancrazio', name: 'San Pancrazio', type: 'quartiere', highlight: 'nord-ovest Verona' },
  { slug: 'croce-bianca', name: 'Croce Bianca', type: 'quartiere', highlight: 'area nord residenziale' },
  { slug: 'palazzolo', name: 'Palazzolo', type: 'quartiere', highlight: 'quartiere est Verona' },
  { slug: 'santa-croce', name: 'Santa Croce', type: 'quartiere', highlight: 'prossimità tangenziale nord' },
  { slug: 'castelnuovo', name: 'Castelnuovo', type: 'quartiere', highlight: 'zona sud verso campagna' },
  { slug: 'bussolengo', name: 'Bussolengo', type: 'comune', highlight: 'Bassona e Gardaland' },
  { slug: 'villafranca-di-verona', name: 'Villafranca di Verona', type: 'comune', highlight: 'aeroporto Catullo' },
  { slug: 'san-giovanni-lupatoto', name: 'San Giovanni Lupatoto', type: 'comune', highlight: 'polo commerciale est' },
  { slug: 'sommacampagna', name: 'Sommacampagna', type: 'comune', highlight: 'residenziale in provincia' },
  { slug: 'pescantina', name: 'Pescantina', type: 'comune', highlight: 'valle dell\'Adige nord' },
  { slug: 'san-martino-buon-albergo', name: 'San Martino Buon Albergo', type: 'comune', highlight: 'cintura est Verona' },
  { slug: 'legnago', name: 'Legnago', type: 'comune', highlight: 'bassa veronese' },
  { slug: 'negrar', name: 'Negrar', type: 'comune', highlight: 'Valpolicella' },
];
